package devin.drools.rules
import devin.drools.data.Order;
import devin.drools.data.OrderLine;
import devin.drools.data.Coupon;
import devin.drools.util.Constants;
import devin.drools.service.CouponService;
import java.math.BigDecimal;

rule "order coupon"
    no-loop true
    lock-on-active true
    when
        $order: Order(channel == Constants.ORDER_CHANNEL_SHOP);
    then
        CouponService.addCoupon($order, 1L, "OR0001", "渠道-实体店-OR0001",
            Constants.COUPON_APPLY_ON_ORDER,
            new BigDecimal(10).setScale(Constants.PRICE_PRECISION, BigDecimal.ROUND_HALF_UP));
end